---

- hosts: target-host
  tasks:
  
  - name: Pull jenkins images
    command: docker pull jenkins:2.60.2

  - name: Create directory for jenkins
    file: 
      path: /docker/jenkins
      state: directory
      mode: 0755

  - name: Create docker-compose
    copy:
        content: |
                 version: "3"

                 services:

                   jenkins:
                      container_name: jenkins
                      image: jenkins:2.60.2
                      restart: always
                      ports:
                        - "8080:8080"
                        - "50000:50000"
                      user: root
                      privileged: true
                      environment:
                        - JAVA_OPTS="-Duser.timezone=Asia/Jakarta"
                      volumes:
                        - /docker/jenkins/jenkins_home:/var/jenkins_home
                        - /etc/localtime:/etc/localtime                
        dest: /docker/jenkins/docker-compose.yml

  - name: Run jenkins container 
    command: docker-compose up -d
    args:
      chdir: /docker/jenkins
